04_Day/04_day_conditionals.md
=> fix extra space

02_Day/02_day_data_types.md
Change the language name from Python to JavaScript
=> Change the wrong language name in day 2 markdown

02_Day/02_day_data_types.md, 03_Day/03_booleans_operators_date.md, 04_Day/04_day_conditionals.md, 05_Day/05_day_arrays.md, 06_Day/06_day_loops.md, 07_Day/07_day_functions.md, 08_Day/08_day_objects.md, readMe.md
Solved: Exercise links were not working (they won't scroll the page to the corresponding exercises)
=> All days' exercise links work now

09_Day/09_day_higher_order_functions.md
added the output to the example
=> find example fix

15_Day/15_day_classes.md
to allow example to be run without returning already defined error
=> default values with constructor fix

Spanish/Día_1/día_1.md
Here I have the complete translation of day 1 (including images)
=> Day 1 translation

26_Day/26_day_dom_day_6.md
=> Day 25 link

30_Day/30_day_dom_day_10.md
Fixing broken link for day 29.
=> Fixing broken link

29_Day/29_day_dom_day_9.md
In this day 29, prev day should be 28 and next 30.
=> Fixing Days Links.

28_Day/28_day_dom_day_8.md
=> Fixing day 27 link

Korea/README.md, Korea/index.html
#280 
First of all, I only worked on the day1 **README.md** including images
=> Translation To Korean (Day1)

Spanish/readme.md
Hi, I joined your telegram group today. I am from Colombia and I wanted to correct some grammatical errors.
=> Grammar Correction

Vietnamese/README.md
Glad to to translate #30DayOfJavaScriot
=> Vietnamese translation

Italian/02_Day_Data_types/02_day_data_types.md, Italian/03_Day_Booleans_operators_date/03_booleans_operators_date.md, Italian/04_Day_Conditionals/04_day_conditionals.md, Italian/05_Day_Arrays/05_day_arrays.md, Italian/06_Day_Loops/06_day_loops.md, Italian/07_Day_Functions/07_day_functions.md, Italian/08_Day_Objects/08_day_objects.md, Italian/09_Day_Higher_order_functions/09_day_higher_order_functions.md, Italian/10_Day_Sets_and_Maps/10_day_Sets_and_Maps.md, Italian/11_Day_Destructuring_and_spreading/11_day_destructuring_and_spreading.md, Italian/12_Day_Regular_expressions/12_day_regular_expressions.md, Italian/13_Day_Console_object_methods/13_day_console_object_methods.md, Italian/14_Day_Error_handling/14_day_error_handling.md, Italian/15_Day_Classes/15_day_classes.md, Italian/16_Day_JSON/16_day_json.md, Italian/17_Day_Web_storages/17_day_web_storages.md, Italian/18_Day_Promises/18_day_promises.md, Italian/19_Day_Closures/19_day_closures.md, Italian/20_Day_Writing_clean_codes/20_day_writing_clean_codes.md, Italian/21_Day_DOM/21_day_dom.md, Italian/22_Day_Manipulating_DOM_object/22_day_manipulating_DOM_object.md, Italian/23_Day_Event_listeners/23_day_event_listeners.md, Italian/24_Day_Project_solar_system/24_day_project_solar_system.md, Italian/25_Day_World_countries_data_visualization_1/25_day_world_countries_data_visualization_1.md, Italian/26_Day_World_countries_data_visualization_2/26_day_world_countries_data_visualization_2.md, Italian/27_Day_Mini_project_portfolio/27_day_mini_project_portfolio.md, Italian/28_Day_Mini_project_leaderboard/28_day_mini_project_leaderboard.md, Italian/29_Day_Mini_project_animating_characters/29_day_mini_project_animating_characters.md, Italian/30_Day_Mini_project_final/30_day_mini_project_final.md, Italian/readMe.md
Lessons from day 1 to day 7 have been translated in Italian for one more language support.
=> Added Day 1-7 Italian language support

Italian/07_Day_Functions/07_day_functions.md, Italian/08_Day_Objects/08_day_objects.md, Italian/09_Day_Higher_order_functions/09_day_higher_order_functions.md, Italian/10_Day_Sets_and_Maps/10_day_Sets_and_Maps.md, Italian/11_Day_Destructuring_and_spreading/11_day_destructuring_and_spreading.md, Italian/12_Day_Regular_expressions/12_day_regular_expressions.md, Italian/13_Day_Console_object_methods/13_day_console_object_methods.md, Italian/14_Day_Error_handling/14_day_error_handling.md, Italian/readMe.md, readMe.md
Added Day 8-14 Italian language support and little corrections to previous files.
Added italian language link to main readMe.md
=> Added Day 8-14 Italian language support

Turkish/05_Day_Arrays/05_day_arrays.md
I translated to 05_Day_Arrays file English to Turkish.
=> 05_Day_Arrays Translated to Turkish

Turkish/19_Day_Closures/19_day_closures.md
An understandable document translation has been made without translating the terms of the Javascript language
=> Translate 19_Day_Closures to Turkish

Spanish/dia_02_tipos_de_datos.md, Spanish/dia_03_Booleanos_Operadores_Date/dia_03_Boleanos_Operadores_Date.md, Spanish/dia_04_Condicionales/dia_04_Condicionales.md, Spanish/dia_05_Arreglos/dia_05_arreglos.md, Spanish/readme.md
Hi @Asabeneh I sent you the first translation of day 3. I continue working on the other translations. Have a nice day
=> Spanish translation day 3 of 30

Spanish/dia_07_Funciones/dia_07_funciones.md, Spanish/dia_08_Objetos/dia_08_objetos.md, Spanish/dia_09_Funciones_De_Orden_Superior/dia_09_funciones_de_orden_superior.md
=> Spanish translation day 8 and 9

Spanish/dia_09_Funciones_De_Orden_Superior/dia_09_funciones_de_orden_superior.md, Spanish/dia_10_Sets_y_Maps/dia_10_sets_y_maps.md, Spanish/dia_11_Desestructuracion_y_Spreading/dia_11_desestructuracion_y_spreading.md
=> Spanish translation day 10 of 30

Spanish/dia_14_Manejo_de_Errores/dia_14_manejo_de_errores.md, Spanish/dia_15_Clases/dia_15_clases.md, Spanish/dia_16_JSON/dia_16_json.md, Spanish/dia_17_Web_storages/dia_17_web_storages.md
day 15, 16, 17. have a nice day.
=> Spanish translation

Portuguese/readMe.md
i'll be working translating this awesome work for begginers brazilians developers, thanks sir.
=> Portuguese Translation

Portuguese/readMe.md, readMe.md
=> link to portuguese translation

RU/README.md
appended other available language links
=> update RU 1 day readme.md
